main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('login', loginUser, name='login'),
    path('register', registerUser, name='register'),
    path('logout', logoutUser, name='logout'),
    path('loginflutter', loginFlutter, name='loginFlutter'),
    path('registerflutter',registerFlutter,name='registerFlutter'),
    path('logoutflutter',logoutFlutter,name='logoutFlutter'),
]

reflekt_io/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import loginUser

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main URLs
    path('', include('main.urls')),
    path(r'login/', loginUser),
    # URL integration
    path('journal/', include('journal.urls', namespace='journal')),
    path('pojok-curhat/', include('pojok_curhat.urls', namespace='pojok_curhat')),
    path('tembok-harapan/', include('tembok_harapan.urls', namespace='tembok_harapan')),
    path('kutipan-penyemangat/', include('kutipan_penyemangat.urls', namespace='kutipan_penyemangat')),
    path('deteksi-depresi/', include('deteksi_depresi.urls', namespace='deteksi_depresi')),
    path('refleksi/', include('refleksi.urls', namespace='refleksi')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
]

tembok_harapan/urls.py
from django.urls import path
from tembok_harapan.views import *

app_name = 'tembok_harapan'

urlpatterns = [
    path('', index, name='index'),
    path('add-harapan', add_harapan, name='add_harapan'),
    path('json-tembok-harapan', json_tembok_harapan, name='json-tembok-harapan'),
    path('add-harapan-flutter',add_harapan_flutter, name='add-harapan-flutter'),
]

tembok_harapan/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class harapan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    harapan = models.TextField()

tembok_harapan/forms.py
from django import forms
from .models import harapan
# Reordering Form and View

class harapanForm(forms.ModelForm):
    class Meta:
        model = harapan
        fields=['title', 'harapan']

tembok_harapan/views.py
import json
from django.core import serializers
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse
from django.http import response
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from tembok_harapan.forms import harapanForm
from django.contrib.auth.decorators import login_required
from .models import harapan

@login_required(login_url='/login/')
def index(request):
    log_user =  request.user
    list_harapan = harapan.objects.filter(user=log_user)
    return render(request, 'harapan_list.html', {'list_harapan':list_harapan})

@login_required(login_url='/login/')
def add_harapan(request):
    if request.method == 'POST':
        form = harapanForm(request.POST)
        if form.is_valid():
            harapan_form = form.save(commit=False)
            harapan_form.user = request.user
            harapan_form.save()
            return response.HttpResponseRedirect('/tembok-harapan')

    else:
        form = harapanForm()

    
    return render(request, 'harapan_form.html', {'form':form})


@login_required(login_url='/login/')
def json_tembok_harapan(request):
    data_harapan = harapan.objects.filter(user=request.user)
    data = serializers.serialize('json', data_harapan)
    return HttpResponse(data, content_type="application/json")

@csrf_exempt
def add_harapan_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
    
        title_flutter = data["title"]
        harapan_flutter = data["harapan"]

        harapan_form = harapan(title = title_flutter, harapan = harapan_flutter, user = request.user)
        harapan_form.save()

        return JsonResponse({"status": "success"}, status=200)
       
    else:
        return JsonResponse({"status": "error"}, status=401)

tembok_harapan/templates/harapan_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Tembok Harapan{% endblock %}

{% block content %}

<!-- Header -->
<header class="ex-header">
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1 text-center">
                <h1>Harapan Baru</h1>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
<!-- end of header -->

<div class="ex-basic-1 pt-5 pb-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Tuliskan Harapanmu</h2>
            </div> <!-- end of col -->
        </div> <!-- end of row -->

        <br>

        <div class="row">
            <div class="col-lg-12">
                
                <!-- Form -->
                <form id="harapan-form" method="POST" action="">
                    {% csrf_token %}
                    <p>Hal apa yang sangat kamu harapkan ?</p>
                    <div class="bulletless-form" id="feeling">
                        {{ form.title }}
                    </div>
                    <p>Apa yang akan kamu lakukan agar kamu dapat mewujudkan harapanmu?</p>
                    <div class="bulletless-form" id="factor">
                        {{ form.harapan }}
                    </div>
                    <br>
                    <div>
                        <input class="btn-solid-lg" name="submit" type="submit" value="Submit" />
                    </div>
                </form>
                <!-- end of harapan form -->

            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div>
{% endblock %}

<script type="text/javascript">
    $(document).on('submit', '#harapan-form', function(e) {
        e.preventDefault();
        var form = $("#harapan-form");

        $.ajax({
            url:'',
            type: 'POST',
            data: form.serialize(),
            dataType: 'json',
            header: {'X-CSRFToken': '{% csrf_token %}'},
            success: function(response) {
                var success = response['success']
                if(success){
                    Swal.fire({
                        icon: 'success',
                        title: 'Terima kasih!',
                        text: 'Pesan Anda sudah terkirim',
                        confirmButtonText: 'OK',
                        confirmButtonColor: '#0b36a8',
                    })

                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Form yang Anda isi tidak valid!',
                        text: 'Silakan mengisi form kembali',
                        confirmButtonText: 'OK',
                        confirmButtonColor: '#0b36a8',
                    })
                }
                document.getElementById("harapan-form").reset();
            },
            error: function(response) {
                Swal.fire({
                        icon: 'error',
                        title: 'Upss, terjadi error...',
                        text: 'Coba refresh halaman ini dan kirim ulang pesan Anda',
                        confirmButtonText: 'OK',
                        confirmButtonColor: '#0b36a8',
                })
                document.getElementById("harapan-form").reset();
            }
        })
    })
</script>

tembok_harapan/templates/harapan_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Tembok Harapan{% endblock %}

{% block content %}

<style> 
    .past-card{
    border-radius: 4px;
    box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
    transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
    }

    .past-card:hover{
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }

    .card-body a{
        position: relative;
        display: inline-block;
        background: #24262a;
        padding: 8px 20px;
        margin-top: 15px;
        border-radius: 20px;
        color: white;
        font-weight: 400px;
        text-decoration: none;
        box-shadow: 0 10px 20px rgba(0,0,0,0.2);
    }
</style>

<!-- Header -->
<header class="ex-header">
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1 text-center">
                <h1>Harapan</h1>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
<!-- end of header -->


<div class="ex-basic-1 pt-5 pb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                {% if list_harapan %}
                    <div class="row">
                        <div class="col-lg-12 riwayat-kegiatan">
                            {% for i in list_harapan %}
                                <div class="card mb-4 past-card">
                                    <div class="card-body">
                                        <h4>{{i.title}}</h4>
                                        <p>{{i.harapan}}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    <h3>Sepertinya, Anda belum pernah membuat harapan.</h3>
                {% endif %}
            </div> 
        </div> 
    </div> 
</div> 

<div class="ex-basic-1 pb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                <h5>Harapan apa yang kamu inginkan ?</h5>
                <br>
                <a class="btn-solid-lg" href="{% url 'tembok_harapan:add_harapan' %}">Tambahkan Harapan</a>
            </div>
        </div> 
    </div> 
</div> 

{% endblock %}