deteksi_depresi/urls.py
from django.urls import path
from .views import phq9, get_phq9_json, fetch_result_flutter, add_result_flutter

app_name = "deteksi_depresi"

urlpatterns = [
    path('', phq9, name='phq9'),
    path('phq9-json', get_phq9_json, name='phq9-json'),
    path('fetch-result-flutter', fetch_result_flutter, name='fetch-result-flutter'),
    path('add-result-flutter', add_result_flutter, name='add-result-flutter'),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('login', loginUser, name='login'),
    path('register', registerUser, name='register'),
    path('logout', logoutUser, name='logout'),
    path('loginflutter', loginFlutter, name='loginFlutter'),
    path('registerflutter',registerFlutter,name='registerFlutter'),
    path('logoutflutter',logoutFlutter,name='logoutFlutter'),
]

reflekt_io/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import loginUser

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main URLs
    path('', include('main.urls')),
    path(r'login/', loginUser),
    # URL integration
    path('journal/', include('journal.urls', namespace='journal')),
    path('pojok-curhat/', include('pojok_curhat.urls', namespace='pojok_curhat')),
    path('tembok-harapan/', include('tembok_harapan.urls', namespace='tembok_harapan')),
    path('kutipan-penyemangat/', include('kutipan_penyemangat.urls', namespace='kutipan_penyemangat')),
    path('deteksi-depresi/', include('deteksi_depresi.urls', namespace='deteksi_depresi')),
    path('refleksi/', include('refleksi.urls', namespace='refleksi')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
]

deteksi_depresi/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class HasilDeteksiDepresi(models.Model):
    date = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    result = models.CharField(max_length=30)

deteksi_depresi/forms.py
from django import forms

class PHQ9Form(forms.Form):
    CHOICES = [(0, ''), (1, ''),
               (2, ''), (3, '')]

    phq_1 = forms.ChoiceField(
        label='Kurang berminat atau bergairah dalam melakukan apapun',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))

    phq_2 = forms.ChoiceField(
        label='Merasa murung, sedih, atau putus asa',
        choices=CHOICES, 
        widget=forms.RadioSelect(attrs={'class':''}))

    phq_3 = forms.ChoiceField(
        label='Sulit tidur/mudah terbangun, atau terlalu banyak tidur',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))
    
    phq_4 = forms.ChoiceField(
        label='Merasa lelah atau kurang bertenaga',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))
    
    phq_5 = forms.ChoiceField(
        label='Kurang nafsu makan atau terlalu banyak makan',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))
    
    phq_6 = forms.ChoiceField(
        label='Kurang percaya diri — atau merasa bahwa Anda adalah orang yang gagal atau telah mengecewakan diri sendiri atau keluarga',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))
    
    phq_7 = forms.ChoiceField(
        label='Sulit berkonsentrasi pada sesuatu, misalnya membaca koran atau menonton televisi',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))
    
    phq_8 = forms.ChoiceField(
        label='Bergerak atau berbicara sangat lambat sehingga orang lain memperhatikannya. Atau sebaliknya; merasa resah atau gelisah sehingga Anda lebih sering bergerak dari biasanya',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))

    phq_9 = forms.ChoiceField(
        label='Merasa lebih baik mati atau ingin melukai diri sendiri dengan cara apapun',
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class': ''}))

deteksi_depresi/views.py
import json
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import HasilDeteksiDepresi
from .forms import PHQ9Form

def phq9(request):
    form = PHQ9Form()

    if request.user.is_authenticated:
        hasil_deteksi = HasilDeteksiDepresi.objects.filter(owner=request.user).first()
    else:
        hasil_deteksi = None

    context = {'form': form, 'hasil_deteksi': hasil_deteksi}
    return render(request, 'phq9.html', context)

def get_phq9_json(request):
    if request.method == 'POST':
        form = PHQ9Form(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            skor = int(form_data['phq_1']) + int(form_data['phq_2']) + int(form_data['phq_3']) + int(form_data['phq_4']) + int(
                form_data['phq_5']) + int(form_data['phq_6']) + int(form_data['phq_7']) + int(form_data['phq_8']) + int(form_data['phq_9'])

            if skor >= 20:
                result = "Depresi berat"
            elif skor >= 15:
                result = "Depresi sedang"
            elif skor >= 10:
                result = "Depresi ringan"
            elif skor >= 5:
                result = "Gejala depresi ringan"
            else:
                result = "Tidak terdapat gejala depresi"

            if request.user.is_authenticated:
                hasil_deteksi = HasilDeteksiDepresi.objects.filter(owner=request.user).first()
                if hasil_deteksi:
                    hasil_deteksi.result = result
                    hasil_deteksi.save()
                else:
                    hasil_deteksi = HasilDeteksiDepresi(owner=request.user, result=result)
                    hasil_deteksi.save()
            return JsonResponse({'result': result})
        else:
            return JsonResponse({'error': form.errors})
    return redirect('deteksi_depresi:phq9')

@csrf_exempt
def add_result_flutter(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            data = json.loads(request.body)
            result = data["result"]
            
            hasil_deteksi = HasilDeteksiDepresi.objects.filter(owner=request.user).first()
            if hasil_deteksi:
                hasil_deteksi.result = result
                hasil_deteksi.save()
            else:
                hasil_deteksi = HasilDeteksiDepresi(owner=request.user, result=result)
                hasil_deteksi.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def fetch_result_flutter(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            hasil_deteksi = HasilDeteksiDepresi.objects.filter(owner=request.user).first()
            if hasil_deteksi:
                return JsonResponse({"result": hasil_deteksi.result, "date": hasil_deteksi.date}, status=200)
        return JsonResponse({"result": "", "date": ""}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

deteksi_depresi/templates/phq9.html
{% extends 'base.html' %}

{% load static %}

{% block title %}PHQ9{% endblock %}

{% block content %}
<!-- Header -->
<header class="ex-header">
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                <h1>Patient Health Questionnaire (PHQ-9)</h1>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
<!-- end of header -->

<!-- Basic -->
<div class="ex-basic-1 pt-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                {% if hasil_deteksi %}
                <div id="past-result" class="card text-center mb-4">
                    <div class="card-header">
                        Hasil Terakhir Deteksi Depresi
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ hasil_deteksi.result }}</h5>
                    </div>
                    <div class="card-footer text-muted">
                        {{ hasil_deteksi.date }}
                    </div>
                </div>
                {% endif %}
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of ex-basic-1 -->
<!-- end of basic -->

<!-- Basic -->
<div class="ex-basic-1 pb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                <form action="{% url 'deteksi_depresi:phq9-json' %}" method="POST" id="phq9form" class="form">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th style="width: 50%">Dalam 2 minggu terakhir, seberapa sering Anda terganggu oleh masalah-masalah berikut?</th>
                                <th style="width: 12.5%" class="text-center">Tidak pernah</th>
                                <th style="width: 12.5%" class="text-center">Beberapa hari</th>
                                <th style="width: 12.5%" class="text-center">Lebih dari seminggu</th>
                                <th style="width: 12.5%" class="text-center">Hampir setiap hari</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for field in form %}
                            <tr>
                                <td><label class="" for="{{ field.auto_id }}">{{ field.label }}</label></th>
                
                                {% for choice in field %}
                                <td class="text-center align-middle">{{ choice }}</th>
                                {% endfor %}
                
                            </tr>
                            {% endfor %}
                            <tr class="table-active">
                                <td>Hasil deteksi depresi</td>
                                <td colspan='4' class="text-center font-weight-bold" id='result'></td>
                            </tr>
                        </tbody>
                    </table>
                    <input class="btn btn-block btn-solid-lg" type="submit" value="Lihat hasil">
                </form>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of ex-basic-1 -->
<!-- end of basic -->
{% endblock %}

{% block script %}
<!-- Scripts -->
<script src="{% static 'js/phq9.js' %}"></script>
{% endblock %}