main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('login', loginUser, name='login'),
    path('register', registerUser, name='register'),
    path('logout', logoutUser, name='logout'),
    path('loginflutter', loginFlutter, name='loginFlutter'),
    path('registerflutter',registerFlutter,name='registerFlutter'),
    path('logoutflutter',logoutFlutter,name='logoutFlutter'),
]

refleksi/urls.py
from django.urls import path
from .views import index, add_kegiatan, add_deskripsi, add_kegiatan_flutter

app_name = "refleksi"

urlpatterns = [
    path('', index, name='index'),
    path('add-kegiatan', add_kegiatan, name='add_kegiatan'),
    path('add-kegiatan-flutter', add_kegiatan_flutter, name='add_kegiatan_flutter'),
    path('add-deskripsi', add_deskripsi, name='add_deskripsi'),
]

reflekt_io/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import loginUser

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main URLs
    path('', include('main.urls')),
    path(r'login/', loginUser),
    # URL integration
    path('journal/', include('journal.urls', namespace='journal')),
    path('pojok-curhat/', include('pojok_curhat.urls', namespace='pojok_curhat')),
    path('tembok-harapan/', include('tembok_harapan.urls', namespace='tembok_harapan')),
    path('kutipan-penyemangat/', include('kutipan_penyemangat.urls', namespace='kutipan_penyemangat')),
    path('deteksi-depresi/', include('deteksi_depresi.urls', namespace='deteksi_depresi')),
    path('refleksi/', include('refleksi.urls', namespace='refleksi')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
]

refleksi/models.py
from django.db import models
from django.contrib.auth.models import User

class Kegiatan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    nama = models.CharField(max_length=40)
    deskripsi = models.CharField(max_length=60)

refleksi/forms.py
from django import forms
from .models import Kegiatan

class KegiatanForm(forms.ModelForm):
    class Meta: 
        model = Kegiatan
        exclude = ['user']

refleksi/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.contrib.auth.decorators import login_required
from .models import Kegiatan
from .forms import KegiatanForm
import json

@login_required(login_url='/login/')
def index(request):
    kegiatan_list = Kegiatan.objects.filter(user=request.user)
    response = {'kegiatan': kegiatan_list, 'user': request.user}
    return render(request, 'refleksi_index.html', response)

@login_required(login_url='/login/')
def add_kegiatan(request):
    form_kegiatan = KegiatanForm(request.POST or None)

    if request.method == "POST" and form_kegiatan.is_valid():
        form = form_kegiatan.save(commit=False)
        form.user = request.user
        form.save()
        return redirect('/refleksi/')

    response = {'form': form_kegiatan }
    
    return render(request, 'refleksi_form.html', response)

@login_required(login_url='/login/')
def add_deskripsi(request):
    form_kegiatan = KegiatanForm(request.POST or None)

    if request.method == "GET":
        kegiatan = Kegiatan.objects.filter(user=request.user)
        data = serializers.serialize("json", kegiatan)
        return HttpResponse(data, content_type="application/json")

    if request.method == "POST" and form_kegiatan.is_valid():
        form = form_kegiatan.save(commit=False)
        form.user = request.user
        form.save()
        
        kegiatan = Kegiatan.objects.filter(user=request.user).last()
        return JsonResponse({'user': str(request.user), 'nama': kegiatan.nama, 'deskripsi':kegiatan.deskripsi})
    
    return JsonResponse({'nama': "", 'deskripsi':""})

@csrf_exempt
def add_kegiatan_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        nama = data["nama"]
        deskripsi = data["deskripsi"]

        form = Kegiatan(
            user = request.user,
            nama = nama,
            deskripsi = deskripsi
        )
        
        form.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

refleksi/templates/refleksi_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Refleksi: Tambah Kegiatan{% endblock %}

{% block content %}
    <link href="{% static 'css/refleksi_style.css' %}" rel="stylesheet" >

    <!-- Header -->
    <header class="ex-header">
        <div class="container">
            <div class="row">
                <div class="col-xl-10 offset-xl-1 text-center">
                    <h1>Refleksi: Tambah Kegiatan</h1>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->

    <!-- Basic -->
    <div class="ex-basic-1 pt-5 pb-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-10">
                    <h4>Silakan menambahkan rekomendasi kegiatanmu</h4>
                </div> <!-- end of col -->
            </div> <!-- end of row -->

            <br>

            <div class="row">
                <div class="col-lg-7">
                    <form method="POST" action="" role="form">
                        {% csrf_token %}
                        <label for="id_nama">Nama kegiatan</label>
                        <input type="text" name="nama" class="form-control" maxlength="40" required id="id_nama">
                        <br>
                        <label for="id_deskripsi">Deskripsi tambahan</label>
                        <input type="text" name="deskripsi" class="form-control" maxlength="60" required id="id_deskripsi">
                        <br>
                        <button type="submit" value="Submit" class='btn-solid-lg'>Tambahkan</button>
                        <a class="btn-solid-lg" href="/refleksi/">Kembali</a>
                    </form>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of ex-basic-1 -->
    <!-- end of basic -->

{% endblock content %}

{% block script %}
    <script src="{% static 'js/refleksi_script.js' %}" type="text/javascript"></script>
{% endblock script%}

refleksi/templates/refleksi_index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Refleksi: Ide Kegiatan{% endblock %}

{% block content %}
    <link href="{% static 'css/refleksi_style.css' %}" rel="stylesheet" >

    <!-- Header -->
    <header class="ex-header">
        <div class="container">
            <div class="row">
                <div class="col-xl-10 offset-xl-1 text-center">
                    <h1>Refleksi: Ide Kegiatan</h1>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->

    <!-- Modal -->
    <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title"><h2>Tambah kegiatan</h2></div>
                </div>
                <form id="kegiatanForm" method="POST" action="" role="form">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="id_nama">Nama kegiatan</label>
                        <input type="text" name="nama" class="form-control" maxlength="40" required id="id_nama">
                        <br>
                        <label for="id_deskripsi">Deskripsi tambahan</label>
                        <input type="text" name="deskripsi" class="form-control" maxlength="60" required id="id_deskripsi">
                    </div>
                    <div class="modal-footer">
                    <button type="submit" value="Submit" class='btn-solid-lg'>Tambahkan</button>
                    <button id="button-close" class='btn-solid-lg' data-dismiss='modal'>Tutup</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end of modal -->

    <div class="cards-1 ex-basic-1 pt-5 pb-5">
        <div class="container">
            {% if kegiatan %}
                <div class="row">
                    <div class="col-lg-12 status-kegiatan">
                        <h2>Kegiatan yang pernah kamu lakukan</h2>
                        <p>Halo {{ user }}! Di bawah ini beberapa kegiatan yang pernah kamu lakukan sebelumnya.</p>
                    </div> <!-- end of col -->
                </div> <!-- end of row -->
                <div class="row">
                    <div class="col-lg-12 riwayat-kegiatan">
                        {% for k in kegiatan %}
                            <div class="card mb-4 past-card">
                                <div class="card-body">
                                    <h4>{{ k.nama }}</h4>
                                    <p>{{ k.deskripsi }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <div class="row">
                    <div class="col-lg-12 status-kegiatan">
                        <h2>Halo {{ user }}!</h2>
                        <p>Belum ada kegiatanmu yang dicatat nih :(</p>
                    </div> <!-- end of col -->
                </div> <!-- end of row -->
                <div class="row">
                    <div class="col-lg-12 riwayat-kegiatan">
                        <!-- kosong -->
                    </div>
                </div>
            {% endif %}
        </div> <!-- end of container -->
    </div> <!-- end of cards-1 -->

    <div class="cards-1 ex-basic-1 pb-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mb-3">
                    <h2>Silakan pilih kegiatan yang akan kamu lakukan</h2>
                    <p>Di bawah ini beberapa rekomendasi kegiatan yang dapat kamu lakukan.</p>
                </div> <!-- end of col -->
            </div> <!-- end of row -->

            <div class="row text-center">
                <div class="col-lg-12" id="card-recomendation">
                    <div class='card mb-4 add-card'>
                        <a class='stretched-link text-decoration-none add-rec' href>
                            <div class='card-body text-center'>
                                <h4>(+) Tambah Rekomendasi</h4>
                            </div>
                        </a>
                    </div>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of cards-1 -->

{% endblock content %}

{% block script %}
    <script src="{% static 'js/refleksi_script.js' %}" type="text/javascript"></script>
{% endblock script%}