deteksi_depresi/urls.py
from django.urls import path
from .views import phq9, get_phq9_json, fetch_result_flutter, add_result_flutter

app_name = "deteksi_depresi"

urlpatterns = [
    path('', phq9, name='phq9'),
    path('phq9-json', get_phq9_json, name='phq9-json'),
    path('fetch-result-flutter', fetch_result_flutter, name='fetch-result-flutter'),
    path('add-result-flutter', add_result_flutter, name='add-result-flutter'),
]

journal/urls.py
from django.urls import path
from journal.views import index, add_journal, get_journal_json, add_journal_flutter

app_name = "journal"

urlpatterns = [
    path('', index, name='index'),
    path('add-journal', add_journal, name='add_journal'),
    path('json', get_journal_json, name='get_json'),
    path('add-journal-flutter', add_journal_flutter, name='add_journal_flutter'),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('login', loginUser, name='login'),
    path('register', registerUser, name='register'),
    path('logout', logoutUser, name='logout'),
    path('loginflutter', loginFlutter, name='loginFlutter'),
    path('registerflutter',registerFlutter,name='registerFlutter'),
    path('logoutflutter',logoutFlutter,name='logoutFlutter'),
]

pojok_curhat/urls.py
from django.urls import path
from pojok_curhat.views import add_pojok_curhat_flutter, index, add_curhat, navbar, curhat_list, json_pojok_curhat

app_name = "pojok_curhat"

urlpatterns = [
    path('', index, name='index'),
    path('json', json_pojok_curhat, name = 'json_pojok_curhat'),
    path('navbar', navbar, name='navbar'),
    path('add-curhat', add_curhat, name='add_curhat'),
    path('curhat-list', curhat_list, name='curhat_list'),
    path('add-curhat-flutter', add_pojok_curhat_flutter, name='add_curhat_flutter'),
]

reflekt_io/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import loginUser

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main URLs
    path('', include('main.urls')),
    path(r'login/', loginUser),
    # URL integration
    path('journal/', include('journal.urls', namespace='journal')),
    path('pojok-curhat/', include('pojok_curhat.urls', namespace='pojok_curhat')),
    path('tembok-harapan/', include('tembok_harapan.urls', namespace='tembok_harapan')),
    path('kutipan-penyemangat/', include('kutipan_penyemangat.urls', namespace='kutipan_penyemangat')),
    path('deteksi-depresi/', include('deteksi_depresi.urls', namespace='deteksi_depresi')),
    path('refleksi/', include('refleksi.urls', namespace='refleksi')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

main/views.py
import json
from django.contrib.auth.backends import UserModel
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

def home(request):
    return render(request, 'index.html')

def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('main:home')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'login.html', context)

def registerUser(request):
    form = CreateUserForm()
    
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('main:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def logoutUser(request):
	logout(request)
	return redirect('main:login')

@csrf_exempt
def loginFlutter(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            # Redirect to a success page.
            return JsonResponse({
              "status": True,
              "username": request.user.username,
              "message": "Successfully Logged In!"
            }, status=200)
        else:
            return JsonResponse({
              "status": False,
              "message": "Failed to Login, Account Disabled."
            }, status=401)

    else:
        return JsonResponse({
          "status": False,
          "message": "Failed to Login, check your email/password."
        }, status=401)

@csrf_exempt
def registerFlutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        username = data["username"]
        email = data["email"]
        password1 = data["password1"]

        newUser = UserModel.objects.create_user(
        username = username, 
        email = email,
        password = password1,
        )

        newUser.save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def logoutFlutter(request):
    try:
        logout(request)
        return JsonResponse({
                    "status": True,
                    "message": "Successfully Logged out!"
                }, status=200)
    except:
        return JsonResponse({
          "status": False,
          "message": "Failed to Logout"
        }, status=401)

main/templates/base.html
<!--  Load static files -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="Sebuah tempat baru yang akan menjadi tempat aman untuk merefleksikan diri, berkeluh kesah, memberikan semangat kepada sesama, dan menyuarakan harapan tanpa rasa takut.">
    <meta name="author" content="reflekt.io">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on Facebook, Twitter, LinkedIn -->
	<meta property="og:site_name" content="" /> <!-- website name -->
	<meta property="og:site" content="" /> <!-- website link -->
	<meta property="og:title" content=""/> <!-- title shown in the actual shared post -->
	<meta property="og:description" content="" /> <!-- description shown in the actual shared post -->
	<meta property="og:image" content="" /> <!-- image link, make sure it's jpg -->
	<meta property="og:url" content="" /> <!-- where do you want your post to link to -->
	<meta name="twitter:card" content="summary_large_image"> <!-- to have large image post format in Twitter -->

    <!-- Webpage Title -->
    <title>{% block title %}{% endblock %} | reflekt.io</title>
    
    <!-- Styles -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;0,700;1,400&family=Poppins:wght@600&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/icofont/icofont.min.css' %}" rel="stylesheet" >
	
	<!-- Favicon  -->
    <link rel="icon" href="{% static 'images/favicon.png' %}">
</head>
<body data-spy="scroll" data-target=".fixed-top">
    
    <!-- Navigation -->
    {% include 'navbar.html' %}
    <!-- end of navigation -->

    <!-- Content -->
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>
    <!-- end of content -->

    <!-- Footer -->
    {% include 'footer.html' %}
    <!-- end of footer -->
    
    <!-- Scripts -->
    <script src="{% static 'js/jquery.min.js' %}"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script> <!-- Bootstrap framework -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="{% static 'js/scripts.js' %}"></script> <!-- Custom scripts -->

    <!-- Additional Scripts -->
    {% block script %}
    {% endblock script %}
</body>
</html>

main/templates/footer.html
<!-- Footer -->
<div class="footer bg-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="social-container">
                    <span class="fa-stack">
                        <a href="https://github.com/reflekt-io/" title="GitHub">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-github fa-stack-1x"></i>
                        </a>
                    </span>
                </div> <!-- end of social-container -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of footer -->  
<!-- end of footer -->


<!-- Copyright -->
<div class="copyright bg-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="p-small">Copyright © Kelompok C04 PTS PBP Semester Gasal, Tahun Ajaran 2021/2022.</p>
            </div> <!-- end of col -->
        </div> <!-- enf of row -->
    </div> <!-- end of container -->    
</div> <!-- end of copyright --> 
<!-- end of copyright -->

main/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Homepage{% endblock %}

{% block content %}
<!-- Header -->
<header id="header" class="header">
    <!-- Picture taken from https://unsplash.com/photos/7FOSJVtUtac -->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="text-container">
                    <h1 class="h1-large">A new safe place, tailored for each individual.</h1>
                    <a class="btn-solid-lg page-scroll" href="#about">Discover</a>
                    {% if user.is_authenticated %}
                    {% else %}
                        <a class="btn-solid-lg" href="{% url 'main:login' %}">Login</a>
                    {% endif %}
                </div> <!-- end of text-container -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of header -->
<!-- end of header -->


<!-- About-->
<div id="about" class="basic-1 bg-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="text-container first">
                    <h2 class="highlight">Kesehatan mental.</h2>
                    <p>Kami yakin bahwa hidup semakin tidak mudah dijalani di bawah bayangan pandemi COVID-19 yang tak kunjung reda. Dengan adanya batasan interaksi dan rasa canggung untuk berinteraksi dengan orang lain yang semakin bertambah, rasa frustrasi dan bingung dalam berkeluh kesah semakin ada.</p>
                </div> <!-- end of text-container -->
            </div> <!-- end of col -->
            <div class="col-lg-4">
                <div class="text-container second">
                    <h2 class="highlight">Kata.</h2>
                    <p>Kata memiliki kekuatan besar yang tidak terduga, baik itu kekuatan yang baik ataupun buruk. Kami yakin bahwa kata dapat meluapkan sebagian besar perasaan yang dialami. Oleh karena itu, kami membangun situs web ini berdasarkan pada kekuatan "kata".</p>
                </div> <!-- end of text-container -->
            </div> <!-- end of col -->
            <div class="col-lg-4">
                <div class="text-container third">
                    <h2 class="highlight">Personal.</h2>
                    <p>Kami yakin bahwa setiap individu memiliki karakter yang unik. Kami juga sangat menghargai privasi pribadi dari setiap orang. Oleh karena itu, kami berusaha semaksimal mungkin untuk merancang situs web ini dengan sifat yang dapat merangkul setiap individu dengan keunikannya masing-masing.</p>
                </div> <!-- end of text-container -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of basic-1 -->
<!-- end of about -->


<!-- Services -->
<div id="services" class="basic-2">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="h2-heading">Fitur</h2>
                <p class="p-heading">Berikut adalah fitur-fitur yang kami tawarkan melalui situs web ini.</p>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
        <div class="row">
            <div class="col-lg-4">
                <div class="text-box feature-block-item">
                    <i class="icofont-pencil-alt-1"></i>
                    <h4>JOURNALING</h4>
                    <p>Tempat pribadi bagi pengguna untuk mencurahkan pikiran dan emosi yang mereka rasakan di sepanjang hari.</p>
                </div> <!-- end of text-box -->
            </div> <!-- end of col -->
            <div class="col-lg-4">
                <div class="text-box feature-block-item">
                    <i class="icofont-aim"></i>
                    <h4>IDE KEGIATAN</h4>
                    <p>Berisi rekomendasi aktivitas untuk meningkatkan ataupun menjaga kesehatan mental berdasarkan hasil penjurnalan pengguna.</p>
                </div> <!-- end of text-box -->
            </div> <!-- end of col -->
            <div class="col-lg-4">
                <div class="text-box feature-block-item">
                    <i class="icofont-ui-text-chat"></i>
                    <h4>POJOK CURHAT</h4>
                    <p>Tempat pribadi bagi pengguna untuk mencurahkan semua pikiran dan emosi yang sedang menghantui mereka.</p>
                </div> <!-- end of text-box -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
        <div class="row">
            <div class="col-lg-4">
                <div class="text-box feature-block-item">
                    <i class="icofont-paper-plane"></i>
                    <h4>TEMBOK HARAPAN</h4>
                    <p>Tempat pribadi bagi pengguna untuk menuliskan semua keinginan yang ingin mereka capai.</p><br>
                </div> <!-- end of text-box -->
            </div> <!-- end of col -->
            <div class="col-lg-4">
                <div class="text-box feature-block-item">
                    <i class="icofont-search-2"></i>
                    <h4>DETEKSI DINI DEPRESI</h4>
                    <p>Alat yang membantu pengguna untuk mengetahui apakah mereka sedang mengalami depresi atau tidak.</p>
                </div> <!-- end of text-box -->
            </div> <!-- end of col -->
            <div class="col-lg-4">
                <div class="text-box feature-block-item">
                    <i class="icofont-quote-left"></i>
                    <h4>KUTIPAN PENYEMANGAT</h4>
                    <p>Tempat bagi pengguna untuk mengirimkan kutipan penyemangat yang nantinya akan dipublikasikan ke publik.</p>
                </div> <!-- end of text-box -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of basic-2 -->
<!-- end of services -->


<!-- Details -->
<div class="split">
    <div class="area-1">
        <!-- Picture taken from https://unsplash.com/photos/lcfZmDhQP5g -->
    </div><!-- end of area-1 on same line and no space between comments to eliminate margin white space --><div class="area-2 bg-gray">
        <div class="container">    
            <div class="row">
                <div class="col-lg-12">
                    <!-- Text Container -->
                    <div class="text-container">
                        <h2>Harapan</h2>
                        <p>Kami berharap situs web ini dapat membantu orang-orang untuk menjalani hidup dengan lebih mudah di masa pandemi.</p>
                        <h5>LEGA</h5>
                        <p>Dengan adanya fitur-fitur yang dapat menyalurkan perasaan setiap individu, kami berharap pengguna situs web ini dapat memberikan rasa nyaman, aman, lega, dan bahagia.</p>
                        <h5>PERCAYA DIRI</h5>
                        <p>Dengan adanya fitur-fitur yang dapat membantu interaksi antar manusia, kami berharap situs web ini dapat mengurangi rasa canggung saat berinteraksi.</p>
                        <h5>POSITIF</h5>
                        <p>Dengan adanya fitur ide kegiatan, kami berharap situs web ini bermanfaat bagi para pengguna dalam menciptakan perasaan yang positif dengan melakukan ide kegiatan yang direkomendasikan.</p>
                    </div> <!-- end of text-container -->
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of area-2 -->
</div> <!-- end of split -->
<!-- end of details -->


<!-- Questions -->
<div class="accordion-1">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="h2-heading">Frequently Asked Questions (FAQ)</h2>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
        <div class="row">
            <div class="col-lg-12">

                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Apakah saya perlu membuat akun untuk menggunakan situs web ini?
                            </button>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body">
                                Anda tidak memerlukan akun untuk melakukan deteksi dini depresi, melihat kutipan penyemangat, serta melihat detail aplikasi dan memberikan saran kepada pengembang aplikasi melalui About Us.
                                Namun, akun pengguna diperlukan untuk menikmati seluruh fitur yang disediakan oleh situs web ini.
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingTwo">
                            <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Dimana saya dapat membuat akun?
                            </button>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                            <div class="card-body">
                                Akun dapat dibuat melalui tautan <a href="{% url 'main:login' %}">ini</a>.
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingThree">
                            <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Apakah keamanan pengguna dijamin aman dan personal?
                            </button>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                            <div class="card-body">
                                Ya, keamanan pengguna dijamin aman dan personal.
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingFour">
                            <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                Tipe kuesioner apa yang digunakan pada deteksi dini depresi?
                            </button>
                        </div>
                        <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                            <div class="card-body">
                                Kami menggunakan kuesioner Patient Health Questionnaire (PHQ-9) untuk modul deteksi dini depresi.
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingFive">
                            <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                Apakah saya dapat memberikan kritik dan saran untuk pengembang?
                            </button>
                        </div>
                        <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
                            <div class="card-body">
                                Ya, Anda dapat memberikan kritik dan saran kepada kami melalui tautan <a href="{% url 'about_us:index' %}">ini</a>.
                            </div>
                        </div>
                    </div>
                </div> <!-- end of accordion -->

            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of accordion-1 -->
<!-- end of questions -->


<!-- About Us -->
<div id="about-us" class="about-us-home bg-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="h2-heading">About Us</h2>
                <p class="p-heading">Untuk mengetahui situs web ini lebih dalam, klik tombol di bawah ini untuk informasi selengkapnya.</p>
                <a class="btn-solid-lg page-scroll" href="{% url 'about_us:index' %}">About Us</a>  
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of form-1 -->  
<!-- end of contact -->
{% endblock %}

main/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #35363a;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: white;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow:0 5px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;
		}
		
		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: black;
			
		}

		.login_btn {
			width: 100%;
			background: #35363a;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}

		.home{
			color: white;
			font-weight: 700;
			font-size: 1.875rem;
			padding-left: 15%;
		}
	</style>

</head>
<body>
	<a class="home" href="{% url 'main:home' %}">reflekt.io</a>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'main:register' %}">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

main/templates/navbar.html
<!--  Load static files -->
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg fixed-top navbar-dark">
    <div class="container">
        
        <!-- Image Logo -->
        <!-- <a class="navbar-brand logo-image" href="{% url 'main:home' %}"><img src="{% static 'images/logo.svg' %}" alt="alternative"></a> --> 

        <!-- Text Logo - Use this if you don't have a graphic logo -->
        <a class="navbar-brand logo-text page-scroll" href="{% url 'main:home' %}">reflekt.io</a>

        <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'deteksi_depresi:phq9' %}">Deteksi Dini Depresi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'kutipan_penyemangat:index' %}">Kutipan Penyemangat</a>
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Jurnal</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'journal:index' %}">Riwayat Jurnal</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'journal:add_journal' %}">Jurnal Baru</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'refleksi:index' %}">Refleksi</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pojok Curhat</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'pojok_curhat:index' %}">Curhat</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'pojok_curhat:curhat_list' %}">Kartu Curhat</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tembok_harapan:index' %}">Tembok Harapan</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about_us:index' %}">About Us</a>
                </li>
                
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <div class="user-name">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user}}</a>
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                    <span class="nav-item social-icons">
                        <span class="fa-stack" title="Login">
                            <a href="{% url 'main:login' %}">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fas fa-user fa-stack-1x"></i>
                            </a>
                        </span>
                    </span>
                {% endif %}
            </ul>
        </div> <!-- end of navbar-collapse -->
    </div> <!-- end of container -->
</nav> <!-- end of navbar -->
<!-- end of navigation -->